# Generated by Django 4.2.5 on 2023-09-28 04:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(default=None)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(default=None, max_length=15)),
                ('state', models.CharField(default=None, max_length=100)),
                ('college', models.CharField(default=None, max_length=100)),
                ('aadhar2', models.CharField(default='', max_length=12, validators=[django.core.validators.MinLengthValidator(12)])),
                ('is_invited', models.BooleanField(default=False)),
                ('is_setup_complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Superuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_head_username', models.CharField(max_length=100)),
                ('team_name', models.CharField(default='SOLO', max_length=100)),
                ('team_size', models.IntegerField(default=1)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.domain')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('aadhar', models.CharField(default='', max_length=12, validators=[django.core.validators.MinLengthValidator(12)])),
                ('is_individual', models.BooleanField()),
                ('domain_of_interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.domain')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='form.team')),
            ],
        ),
    ]
