# Generated by Django 4.2.5 on 2023-09-28 04:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_delete_coordinator_delete_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(default=None)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(default=None, max_length=15)),
                ('state', models.CharField(default=None, max_length=100)),
                ('college', models.CharField(default=None, max_length=100)),
                ('aadhar2', models.CharField(default='', max_length=12, validators=[django.core.validators.MinLengthValidator(12)])),
                ('is_invited', models.BooleanField(default=False)),
                ('is_setup_complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Superuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
