# Generated by Django 4.2.5 on 2023-09-28 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_alter_coordinator_college_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coordinator',
            old_name='aadhar2',
            new_name='aadhar',
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='date_of_birth',
            field=models.DateField(default='2023-12-12'),
        ),
    ]
