# Generated by Django 4.2.5 on 2023-09-28 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_rename_aadhar2_coordinator_aadhar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinator',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='mobile',
            field=models.IntegerField(default='', max_length=15),
        ),
    ]
