# Generated by Django 4.2.5 on 2023-09-28 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_coordinator_password_alter_coordinator_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinator',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
