# Generated by Django 4.2.5 on 2023-09-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0007_coordinator_is_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinator',
            name='last_login',
            field=models.CharField(default='2023-09-28 04:16:42.041659', max_length=100),
        ),
    ]
