# Generated by Django 4.2.5 on 2023-09-28 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0008_coordinator_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinator',
            name='password',
        ),
    ]
