# Generated by Django 4.2.5 on 2023-09-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0009_remove_coordinator_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinator',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
    ]
