# Generated by Django 4.2.5 on 2023-09-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0012_participant_edited_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='edited_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
