# Generated by Django 4.2.5 on 2023-09-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0017_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='current_session_id',
            field=models.CharField(blank=True, default=1, max_length=32, null=True),
        ),
    ]
