# Generated by Django 4.2.5 on 2023-10-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0019_alter_participant_email_alter_participant_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='mobile',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
