# Generated by Django 4.2.5 on 2023-10-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0020_userprofile_last_login_alter_participant_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_checkedin',
            field=models.BooleanField(default=False),
        ),
    ]
