# Generated by Django 4.2.5 on 2023-10-12 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0024_state_participant_meals_participant_participant_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='participant',
            name='meals',
            field=models.ForeignKey(null=True,blank=True, on_delete=django.db.models.deletion.CASCADE, to='form.meals'),
        ),
    ]
