# Generated by Django 4.2.5 on 2023-10-25 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0027_alter_participant_meals'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_qrassigned',
            field=models.BooleanField(default=False),
        ),
    ]
