# Generated by Django 4.2.5 on 2023-11-01 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("form", "0028_participant_is_qrassigned"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParticipantType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="participant",
            name="participant_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="form.participanttype",
            ),
        ),
    ]
